### PR TITLE
Fix the hyperlink bugs in table of contents

### PR DESCRIPTION
**Pull request by KexinFeng**
There was some bugs in the table of contents, where abstract links to wrong page.

Now it is fixed.
I also added a line of content in the table of contents

### CODE REVIEW

**Comment by agude** [comment]
Hi @KexinFeng! Thanks for the PR!

Can you update it to just be the minimal change to fix the linking error? Currently there are 1100 lines changed, mostly due to whitespace it looks like.

Thanks!

**Comment by KexinFeng** [comment]
I have updated it with minimum change. But still github shows that all the file is editted. Something must be wrong with github.
The difference between this commit and the last commit is that in the last commit, I also deleted some commented code.

**Comment by agude** [comment]
I'll take a look at it tomorrow!

**Comment by agude** [comment]
Ok, here is a screenshot of the problem before the PR, you can see the hyperlink is to `ii` instead of `iii` as it should be.
abstract
[thesis_pre_pr.pdf](https://github.com/agude/UMN-PhD-Thesis-Template/files/7810488/thesis_pre_pr.pdf)

The patch fixes this! See example PDF: 
[thesis_post_pr.pdf](https://github.com/agude/UMN-PhD-Thesis-Template/files/7810496/thesis_post_pr.pdf)

Now let me see if I can fix the whitespace issue.

**Comment by agude** [comment]
OK! Figured out the whitespace issue! It's windows linefeeds vs unix linefeeds.

I'll strip them out and then it should be good to go.

Screenshot from 2022-01-04 13-30-38

**Comment by KexinFeng** [comment]
Got it. Thanks for figuring this out!
By the way, in case it is not clear, the bug about the link before the
patch was that, after clicking through, it goes to the wrong place. The fix
is to add \phantomsection which belongs to hyperlink package.

Best,
Kexin

**Comment by agude** [comment]
Thanks for the update @KexinFeng! I'm going to close this and continue working on #6 where I have edit rights. :-)

**Pull request closed without merging**
